<div id="Panel_771"  class="panel-h-box" style="margin-top:20px;margin-right:20px;width:320px;float:left;overflow:hidden;">
    <div class="index-hd1">
      <h2 class="tit">{dede:field name='typename'/}</h2>
      <a class="more fr" href="{dede:field name='typeurl'/}">more</a> </div>
    <div class="panel-h-bdbox">
      <div class="h-contactIntrobox">{dede:arclist titlelen='60' row='8'}
      <img src="{dede:global.cfg_templets_skin/}/images/index_16.jpg" style="float:left;margin-right:15px;" />
        <p> {dede:myad name='dddd'/}<a href="[field:arcurl /]">详情&gt;&gt;</a> </p>
        {/dede:arclist}
      </div>
    </div>
  </div>