<?php
$z[0]=Array("field","",176,205);
$z[0][4]['name']="typename";
$z[1]=Array("field","",243,271);
$z[1][4]['name']="typeurl";
$z[2]=Array("arclist","\r\n      <img src=\"{dede:global.cfg_templets_skin/}/images/index_16.jpg\" style=\"float:left;margin-right:15px;\" />\r\n        <p> {dede:myad name='dddd'/}<a href=\"[field:arcurl /]\">详情&gt;&gt;</a> </p>\r\n        ",360,621);
$z[2][4]['titlelen']="60";
$z[2][4]['row']="8";

?>