<li>
                  <div  class="pic"><a  href="[field:arcurl/]"  title="[field:title/]"><img  src="[field:litpic/]"  alt="[field:title/]"    style="width: 198px; height: 121px;"></a></div>
                  <div  class="txt"> <a  class="name"  href="[field:arcurl/]"  title="[field:title/]">[field:title/]</a>
                    <p  class="intro"> [field:description/]...</p>
                    <span  class="time">[field:pubdate function="MyDate('Y.m.d',@me)"/]</span> </div>
                </li>