<li>
                <div  class="product-list-div">
                  <div  class="product-list-img"><a  href="[field:arcurl/]"  title="[field:title/]"><img  src="[field:picname/]"  alt="[field:title/]"   style="width: 200px; height: 120px; padding: 9px 15px;"></a></div>
                  <div  class="product-list-url"><a  href="[field:arcurl/]"  title="[field:title/]">[field:title/]...</a></div>
                </div>
              </li>