<?php
$z[0]=Array("channel","\r\n     <a href=\"[field:typelink/]\">[field:typename/]</a> |\r\n     ",76,191);
$z[0][4]['row']="6";
$z[0][4]['type']="top";
$z[1]=Array("global","",238,259);
$z[1][4]['name']="cfg_dz";
$z[2]=Array("global","",288,314);
$z[2][4]['name']="cfg_banquan";
$z[3]=Array("global","",1014,1035);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",1259,1281);
$z[4][4]['name']="cfg_qqq";
$z[5]=Array("global","",1503,1535);
$z[5][4]['name']="cfg_templets_skin";

?>