<?php
$z[0]=Array("global","",248,280);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",428,460);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",608,634);
$z[2][4]['name']="cfg_dianhua";
$z[3]=Array("channelartlist","\r\n          <li class=\"\"> <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n            <ul class=\"nav-sub clearfix\">\r\n              {dede:channel type='son' noself='yes'}\r\n              <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",1206,1610);
$z[3][4]['typeid']="top";

?>